### ISSUE TITLE
Add support for PipelineDecider

### ISSUE THREAD

**Issue by Kahbazi** [serilog/serilog-sinks-elasticsearch#135] opened 2017-12-19 08:23 UTC
**Does this issue relate to a new *feature* or an existing *bug*?**
- [ ] Bug
- [x] New Feature

I need to index different logs to different pipelines based on their LogEvent.

I implemented the feature. I add `PipelineNameDecider` property to `ElasticsearchSinkOptions` and set the pipeline name in `ElasticsearchSink`, and It's working! 

Is there anything that I'm missing? Is there someplace else that needs to be changed?

**Comment by mivano** [comment] 2018-01-18 23:15
Merged and released. Be aware that this is not implemented for the durable sink version at the moment. The issue is here that the LogEvent is missing due to the fact that the data are actually no longer logevents. IndexDecider is facing the same issue here BTW.

**Closed by mivano** 2018-01-18 23:15 UTC
