### ISSUE TITLE
Missing {"@ in body

### ISSUE THREAD

**Issue by JakobVork** [serilog/serilog-sinks-elasticsearch#102] opened 2017-03-08 13:39 UTC
Hi,

I have been using serilog for some time now, and have noticed that we once in a while are missing some logs. When I looked into what might caused this I found the following:

First I created a test API that recieved a call and when logged it into a bufferFile (That never miss a log btw). 
I when created a program, that sent 5000 requests to the API. I could see 5000 logs in the bufferFile, but only 4999 logs when I looked at kibana.

I when looked at the network traffic, and found the following:
![image](https://cloud.githubusercontent.com/assets/10922674/23705814/d0c69882-040b-11e7-9f4b-113ce3fef522.png)

If we take a look on the server running elasticsearch it gives this error:
![image](https://cloud.githubusercontent.com/assets/10922674/23705689/58c05756-040b-11e7-97d8-5d2a3778206b.png)

So, from what I can see is that serilog sometimes cuts {"@ away from timestamp. I've tried to run it multiple times, but it does not always happen. (Often need to run it 4-10 times before I see the error again). It is however always the second log that fails.
The bufferFile does not cut away {"@ as shown below:
![image](https://cloud.githubusercontent.com/assets/10922674/23705542/98e6156a-040a-11e7-8019-56763d742308.png)

Not sure why this happens, and especially why this only happens sometimes?

Currently running with ElasticSearch 5.2.1 and Kibana 5.2.1.
The nuget package I use is Serilog.Sinks.Elasticsearch version 5.0.0 (depend on serilog version 2.2.1)

**Comment by nblumhardt** [comment] 2017-03-09 02:50
This sounds like https://github.com/serilog/serilog-sinks-seq/issues/28 - caused by `HttpLogShipper` expecting the (three-byte) Unicode BOM, but more recent versions of Serilog.Sinks.File (and RollingFile) defaulting to no-BOM.

**Comment by JakobVork** [comment] 2017-04-10 10:18
I have now tried to upgrade Serilog.Sinks.File to version 3.2.0, but the behavior is still the same. (Even though, the original dep. was => 3.0.1, and therefore still newer than the mentioned in the link you provided).

**Comment by nblumhardt** [comment] 2017-04-10 21:47
If the issue is the linked one, a fix will be required in this repository.

The fix is: https://github.com/serilog/serilog-sinks-seq/commit/6c0b308efab7aba2062f00b1b83d3749e6d43bfb

If anyone can PR this I can help with review etc.

Cheers,
Nick

**Comment by mivano** [comment] 2018-01-18 23:26
This one is merged in v 5.5

**Closed by mivano** 2018-01-18 23:26 UTC
